name = "prot"
version = "0.0.1"
mode = "dev"
protocol = "http"
host = "localhost"
port = 9000
public_path = "/public"

[mysql]
host = "localhost"
port = 3306
username = "root"
password = "111111"
db = "prot"

[log]
dir = "logs"
