name = "prot"
version = "0.0.1"
mode = "dev"
protocol = "http"
host = "localhost"
port = 9000
public_path = "/public"
debug = true

[mysql]
host = "localhost"
port = 3306
username = "root"
password = "111111"
db = "prot"

[log]
dir = "logs"
format = ""
mode = ""  # close, file, stdout
access = true  # 是否记录浏览器访问系统时产生的日志